name: Generate static site
run-name: ${{ github.actor }} has triggered the generation. 🚀
on: 
  push: 
    branches: 
    - master
jobs:
  Generate-Static-Site:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with: 
          node-version: "20.12.0"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install corepack
        run: corepack enable
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Install yarn
        run: yarn install
      - name: Build static site  
        run: yarn start build production
      - name: Deploy
        run: ./publish.sh
